baseURL = "https://www.saturnspraying.com/"
title = "Saturn Spraying Systems"

languageCode = "en-us"
DefaultContentLanguage = "en"

relativeURLs = true
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
canonifyURLs = true
paginate = 8
darkmode_js = ["assets/js/darkmode.js"]
enableInlineShortcodes = true
timeout = 60000

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]


[permalinks]
    blog = "/:title"
    categories = "/:title"
    tags = "/:title"

[params]
author = "Saturn Spraying Ltd"
authorimage = "../assets/images/global/author.webp"
github = "https://github.com/imobilize/saturnspraying"
facebook = "https://www.facebook.com/saturnsprayingltd"
og_image = "/images/saturn_spraying_systems.png"
sitename = "Saturn Spraying Systems"
twitter = "@saturnspraying"
description = "Specialists in Food Spraying Technology, Food Spraying Machines and Food Spraying Equipment. Food Spraying Products exported worldwide"
logo = ""
keywords = "fruit glaze sprayers, automatic fruit glaze sprayer, automatic fondant sprayers, amanual fondant sprayer, finishing machine,chocolate sprayers,butter sprayer,egg wash sprayers,egg wash spraying,egg glaze spraying,egg glaze sprayer,disk sprayer,spray-mix,depositiors,food processing machines,baking equipment,depositing,pizzabase spraying,waterfall depositors,oil spraying,milk wash spraying,milk spraying,disc spraying,disk sprayer,liquid flovouring,liquid flavouring,liquid flavoring,oil deposition,rademaker,fritsch,rheon,kortlever,bakon,arcall,acrivarn,repco,tromp,connolly international,peeters,alimetec,anditec,artiso,efca"
home = "Home"
# Google Analitycs
googleAnalitycsID = "" # Your ID

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2



[taxonomies]
category = "categories"
tag = "tags"

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true

[menu]
    
  [[menu.main]]
  name = "About"
  URL = "book"
  weight = 1

  [[menu.main]]
  name = "Reviews"
  URL = "reviews"
  weight = 2

  [[menu.main]]
  name = "Chapters"
  URL = "chapters"
  weight = 3
  
  [[menu.main]]
  name = "Author"
  URL = "author"
  weight = 4
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 5
  
  [[menu.main]]
  name = "Free Resources"
  URL = "resources"
  weight = 6

[module]
  [module.hugoVersion]
    extended = true
    min = "0.111.3"
